POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization:  bearer 1eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhamlpODIhIiwiaWQiOiI2MmRjZjJiZDQ5OWExYTVkNTU0MGJkNDciLCJpYXQiOjE2NTg2NTcwMzQsImV4cCI6MTY1ODY2MDYzNH0.6HrsGLkl3sTLeRKB5fVZ9UayiwThI0Fv99Sj-ng3a2A

{
    "title": "aajii82 blog",
    "author": "Irmeli",
    "url": "http://www.blog.com",
    "likes": 1,
    "userId": "62dcf2bd499a1a5d5540bd47"
}